# copy this config into a yaml file 'app_config.yaml' in the same directory
# and enter the twitter api key and secret here.

# email sender and pass is used by the error catcher to send crash reports
# in release mode and can be omitted.

twitter:
  consumer_key: ""
  consumer_secret: ""

email:
  sender: ""
  pass: ""
