name: harpy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  oauth1: ^1.0.4
  json_annotation: ^2.0.0
  logging: ^0.11.3+2
  intl: ^0.15.7
  cached_network_image: ^0.5.0+1
  photo_view:
    git: https://github.com/robertodoering/photo_view.git
  scoped_model: ^1.0.1
  flutter_material_color_picker: ^0.0.5
  flutter_colorpicker: ^0.2.5
  flare_flutter: 1.3.13 # todo: update when it works with flutter stable

  flutter_twitter_login:
    git: git://github.com/robertodoering/flutter_twitter_login.git
  url_launcher: ^5.0.1
  video_player: ^0.10.0+2
  webview_flutter: ^0.3.6
  path_provider: ^0.4.1
  connectivity: ^0.4.2
  catcher: # todo: update to pub release on next catcher release (0.1.5+)
    git: https://github.com/robertodoering/catcher.git

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  mockito: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - app_config.yaml
    - assets/flare/

  fonts:
  - family: Comfortaa
    fonts:
    - asset: assets/fonts/Comfortaa-Light.ttf
      weight: 300
    - asset: assets/fonts/Comfortaa-Regular.ttf
    - asset: assets/fonts/Comfortaa-Bold.ttf
      weight: 700

  - family: OpenSans
    fonts:
    - asset: assets/fonts/OpenSans-Light.ttf
      weight: 300
    - asset: assets/fonts/OpenSans-Regular.ttf
    - asset: assets/fonts/OpenSans-Bold.ttf
      weight: 700
