name: harpy
description: A Twitter app built with Flutter.

publish_to: 'none'

# android/version.properties is used to manage the versions
version: 0.0.0

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # packages
  cached_network_image: ^2.2.0+1
  dart_twitter_api: ^0.3.4
  flare_flutter: ^2.0.6
  flutter_bloc: ^6.0.1
  flutter_colorpicker:
    # todo: use pub version when PR gets merged and released: 
    #   https://github.com/mchome/flutter_colorpicker/pull/28
    git: https://github.com/robertodoering/flutter_colorpicker
  flutter_material_color_picker: ^1.0.5
  flutter_reorderable_list: ^0.1.4
  get_it: ^4.0.2
  intl : ^0.16.1
  logging: ^0.11.4
  provider: ^4.3.1
  sentry: ^3.0.1
  timeago: ^2.0.27
  url_launcher: ^5.4.10
  yaml: ^2.2.1
  
  # plugins
  connectivity: '>=0.4.9 <2.0.0'
  device_info: '>=0.4.2+4 <2.0.0'
  firebase_analytics: ^6.0.0
  flutter_twitter_login:
    git: git://github.com/robertodoering/flutter_twitter_login.git
  package_info: '>=0.4.1 <2.0.0'
  shared_preferences: '>=0.5.8 <2.0.0'
  video_player: '>=0.10.11+2 <2.0.0'

dev_dependencies:
  bloc_test: ^7.0.2
  build_runner: ^1.7.1
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.3
  mockito: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/config/
    - assets/flare/
  
  fonts:  
  - family: Comfortaa
    fonts:
    - asset: assets/fonts/Comfortaa-Light.ttf
      weight: 300
    - asset: assets/fonts/Comfortaa-Regular.ttf
    - asset: assets/fonts/Comfortaa-Bold.ttf
      weight: 700

  - family: OpenSans
    fonts:
    - asset: assets/fonts/OpenSans-Light.ttf
      weight: 300
    - asset: assets/fonts/OpenSans-Regular.ttf
    - asset: assets/fonts/OpenSans-Bold.ttf
      weight: 700
