name: harpy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  oauth1: ^1.0.4
  json_annotation: ^2.0.0
  logging: ^0.11.3+2
  intl: ^0.15.7
  cached_network_image: ^0.8.0
  photo_view: ^0.3.3
  provider: ^2.0.1+1
  flutter_material_color_picker: ^0.0.5
  flutter_colorpicker: ^0.2.5
  flare_flutter: ^1.5.1
  flushbar: 1.5.3

  flutter_twitter_login:
    git: git://github.com/robertodoering/flutter_twitter_login.git
  url_launcher: ^5.0.1
  video_player: ^0.10.0+2
  webview_flutter: ^0.3.6
  path_provider: ^0.5.0+1
  connectivity: ^0.4.2
  catcher: ^0.1.5
  shared_preferences: ^0.5.2+1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  mockito: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - app_config.yaml
    - assets/flare/

  fonts:
  - family: Comfortaa
    fonts:
    - asset: assets/fonts/Comfortaa-Light.ttf
      weight: 300
    - asset: assets/fonts/Comfortaa-Regular.ttf
    - asset: assets/fonts/Comfortaa-Bold.ttf
      weight: 700

  - family: OpenSans
    fonts:
    - asset: assets/fonts/OpenSans-Light.ttf
      weight: 300
    - asset: assets/fonts/OpenSans-Regular.ttf
    - asset: assets/fonts/OpenSans-Bold.ttf
      weight: 700
