name: harpy
description: A Twitter app built with Flutter.

publish_to: 'none'

# android/version.properties is used to manage the versions
version: 0.0.0

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # packages
  cached_network_image: ^2.5.0
  cupertino_icons: ^1.0.0
  dart_twitter_api: ^0.3.5
  downloads_path_provider: ^0.1.0
  equatable: ^1.2.6
  flare_flutter: ^2.0.6
  flutter_bloc: ^6.1.2
  flutter_colorpicker:
    # todo: use pub version when ^0.3.6 gets released
    git: https://github.com/robertodoering/flutter_colorpicker
  flutter_feather_icons: ^1.0.3
  flutter_material_color_picker: ^1.0.5
  flutter_reorderable_list: ^0.1.5
  get_it: ^5.0.6
  humanize: ^0.3.0
  intl : ^0.16.1
  like_button: ^1.0.4
  logging: ^0.11.4
  mime_type: ^0.3.2
  provider: ^4.3.3
  sentry: ^3.0.1
  timeago: ^2.0.29
  url_launcher: ^5.7.8
  visibility_detector: ^0.1.5
  yaml: ^2.2.1

  # plugins
  connectivity: ^2.0.2
  device_info: '>=0.4.2+4 <2.0.0'
  file_picker: ^2.1.6
  firebase_analytics: ^7.0.1
  flutter_ffmpeg: ^0.3.1
  flutter_downloader: ^1.5.2
  flutter_twitter_login:
    git: git://github.com/robertodoering/flutter_twitter_login.git
  keyboard_visibility: ^0.5.6
  package_info: '>=0.4.1 <2.0.0'
  path_provider: ^1.6.27
  permission_handler: ^5.1.0+2
  share: '>=0.6.5+4 <2.0.0'
  shared_preferences: '>=0.5.8 <2.0.0'
  video_player: ^1.0.1

dev_dependencies:
  bloc_test: ^7.1.0
  build_runner: ^1.11.1
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1
  mockito: ^4.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/flare/
    - android/fastlane/metadata/android/free/en-US/changelogs/

  fonts:
  - family: Comfortaa
    fonts:
    - asset: assets/fonts/Comfortaa-Light.ttf
      weight: 300
    - asset: assets/fonts/Comfortaa-Regular.ttf
    - asset: assets/fonts/Comfortaa-Bold.ttf
      weight: 700

  - family: OpenSans
    fonts:
    - asset: assets/fonts/OpenSans-Light.ttf
      weight: 300
    - asset: assets/fonts/OpenSans-Regular.ttf
    - asset: assets/fonts/OpenSans-Bold.ttf
      weight: 700

  - family: NotoSans
    # used as a fallback font
    # covers a lot of scripts and obscure unicode characters
    # https://fonts.google.com/specimen/Noto+Sans
    fonts:
      - asset: assets/fonts/NotoSans-Regular.ttf
      - asset: assets/fonts/NotoSans-Bold.ttf
        weight: 700
